package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class MainFXController {
	@FXML
	private AnchorPane btnID;
	@FXML
	private Button btnUp;
	@FXML
	private Label lblNumber;
	@FXML
	private Button btnDown;
	@FXML
	private ImageView imgView;
	@FXML
	private Button btnId;

	// Event Listener on Button[#btnUp].onAction
	@FXML
	public void btnUpClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDown].onAction
	@FXML
	public void btnDownClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#imgView].onMouseClicked
	@FXML
	public void imgClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnId].onAction
	@FXML
	public void btnBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
